### ISSUE TITLE
RGBA format can be written to a playlist file but not read back

### ISSUE THREAD

**Issue by S-Fe** [IENT/YUView#148]
If you directly load a raw "RGB**A** 8 bit" video, YUView (version 2.0-194-gd0268d6) will default to assuming **RGB** 8bit format, which of course leaves the video "scrambled". This can be manually corrected by setting the "RGB Format" to RGBA 8bit.

After the manual setting, if you save the playlist (_and view the XML with a text editor_), it appears to correctly set the format, i.e. "<pixelFormat>RGBA 8bit</pixelFormat>"

Unfortunately, if you then try to load that playlist file, it doesn't appear to parse/recognise the XML correctly and reverts back to RGB/unknown.

**Comment by S-Fe** [comment]
Actually, it's worse than that. It doesn't seem to cope with RGB formats in playlists either. 

For example, if you save a playlist for an RGB video, it will contain
  _\<pixelFormat>RGB 8bit\</pixelFormat>_

If you then try to load that playlist file, the video will not display and the  "RGB File Properties" will have invalid data, e.g start = -1, End = -1.

Saving this in turn as a playlist, you'll find it contains the following;
  _\<pixelFormat>Unknown Pixel Format\</pixelFormat>_
which seems to indicate it didn't parse the .playlist file correctly.

**Comment by ChristianFeldmann** [comment]
Thanks for reporting this. This happened because the RGB format could not successfully be determined. I improved handling of RGB formats in the new_compression_file_reading branch. I set a custom format and saved / loaded it into a playlist and it worked.

If you want to, please try it out. If you are using windows, the compiled appveyor aritfacts are [here](https://ci.appveyor.com/project/aachenmax/yuview/build/1.0.158/artifacts).

**Comment by S-Fe** [comment]
Many thanks. That version seems to have fixed the problem.
