### ISSUE TITLE
Zoom experience is not good

### ISSUE THREAD

**Issue by doyee** [IENT/YUView#195]
hi guys,
       As you know , It can zoom by cmd+ cmd-,    but we like double finger scaling on MacOS, 
Can you improve it.

thanks

**Comment by ChristianFeldmann** [comment]
This is a very specific feature. Unfortunately I don't have a Mac to test this. But maybe I can borrow one somewhere.

**Comment by kloppjp** [comment]
I've had a chance to run it on a MacBook, the current zoom experience is indeed not useful. I'm not a Qt-on-Mac expert so I'll just briefly state my observations

- If `wheelEvent` is present, then everything you do with two fingers ends up being a mouse wheel event at high sensitivity (you move a few millimeters and your frame isn't even visible anymore because of the large number of wheel events generated)
- If `wheelEvent` is commented out in header & source, you will receive `GestureEvent` in the regular `event` handling function. This is working 50%: zoom speed is acceptable, but the zoom center isn't taken into account (always the center of the frame). 

I wasn't able to catch any `QNativeGestureEvent` though (even printing out every single event going through `event` didn't reveal any), so the placeholder you've left in https://github.com/IENT/YUView/blob/9266eb5be04238edebab4435a865b36a0fa854c7/YUViewLib/src/ui/views/MoveAndZoomableView.cpp#L472 is never visited. 

Some ideas to fix:
- Disable `wheelEvent` under MacOS and fix the gesture event handling so that the current cursor position is probably taken into account (I don't know if that's possible to fix or a bug endemic to Qt). The disadvantage might be that if one uses a Mac with a regular PC mouse and attempts to use the wheel, nothing will happen.
- Continue to use `wheelEvent` but filter the events, i.e. process only every 10th event so that sensitivity gets toned down. This, though kind of weird, would probably be quick and re-enable zooming via trackpad with the only disadvantage that it's a scrolling gesture that does the zoom instead of a pinch.
- Dig into Qt to figure out why it isn't doing what it should... (Good luck :P)

**Comment by ChristianFeldmann** [comment]
Hi thanks for your evaluation. I would actually prefer the last option to get a clean solution. There must be some correct way to do this on macOS. Afterall Qt has support for this. 
I also have a mac right now and will take a look at this when I have some time. But I already tested exactly this and can confirm this issue. I also observed that zooming using the "two-finger up/down" gesture was really horrible and much too fast.

**Comment by ChristianFeldmann** [comment]
So the new solution is to just handle the fine grain wheel events that QT emits under MACOS correctly. Actually the same thing also happens on Windows with a  good touchpad. All offsets and zoom levels are now floats and are handle to do very smooth zooming. 
Now everyone can enjoy smooth zooming on the MAC. Thanks again for the report. I don't have a Mac so I would have never spotted this.
