### ISSUE TITLE
Extended statistics are not visualized for some blocks

### ISSUE THREAD

**Issue by Mitigooli** [IENT/YUView#408]
Extended statistics are not visualized for some blocks in a sequence. 

[extended_stats.csv](https://github.com/IENT/YUView/files/7039020/extended_stats.csv)

Attached is an example that provides extended statistics for 128x128 blocks in a 416x240 video stream, 8 blocks (0-7) in each frame. Blocks 4,6 and 7 in frame 5 are not visualized at all. The same issue for blocks 4, 5, 6 and 7 in frame 8. Similar issues exist in other frames 16, 47, 108 and more.

I have observed that I can go around this issue if I set the Type ID of the first block (block 0) in the first frame (POC 0) of the sequence equal to 0. Probably this gives some clue for where to find the bug in your code.

**Comment by ChristianFeldmann** [comment]
Hi. Sorry that it took so long but I finally looked further into this. This does not look like a bug to me but this is a problem with your stats file. The problem is that the POC / Type data must not be mixed. I also added this Note to the [wiki ](https://github.com/IENT/YUView/wiki/Statistics-Extension-Syntax) where this was not clearly described:

**Note:** The order of the entries in the stats file is important. For performance reasons we do not support a random mixture of POC and type values. Internally, we save a pointer into the file for each POC/type combination for efficient on the fly parsing. This means that all values for each combination of POC and Type must be grouped together in the file. If this is not the case then part of the data will not be displayed.

From the file that you provided:

```
5;0;0;128;128;7;0
5;128;0;128;128;7;0
5;256;0;128;128;7;0
5;384;0;128;128;6;0
5;0;128;128;128;7;0
5;128;128;128;128;4;0
5;256;128;128;128;7;0
5;384;128;128;128;4;0
```

It will work if you order the entries like this:

```
5;0;0;128;128;7;0
5;128;0;128;128;7;0
5;256;0;128;128;7;0
5;0;128;128;128;7;0
5;256;128;128;128;7;0
5;128;128;128;128;4;0
5;384;128;128;128;4;0
5;384;0;128;128;6;0
```

Sorry that this was not more clearly stated in the stats format definition.
