### ISSUE TITLE
New HM addon does not work

### ISSUE THREAD

**Issue by adminy** [IENT/YUView#89]
LibDe265 seems to open all kind of raw videos, but HM looks like it isn't working for any format. 

Using Latest Version on windows 10.

**Comment by ChristianFeldmann** [comment]
Hi! Thanks for the report. I think I understand what you mean. Currently we do ship libde265, but we do not ship a compiled binary of the HM reference software. There are some licencing/patent things that I would like to clear up before including it in the installer. If you want to use the HM reference decoder libaray, you can download it at https://github.com/ChristianFeldmann/libHM/releases. Just place it into the libde265 subfolder or specify the path to it in the settings dialog.
Christian

**Comment by adminy** [comment]
Ok so everything worked perfectly, In fact it got me so interested that I decided to compile the HM for linux myself from your source. It worked perfectly fine. and I compiled the project YUView as well to linux. Strange enough I only got 1 binary when I built it. Still I ran the binary and it worked no problem. And Thanks for leaving an option in the settings to select the HM library. I selected it while I had the video already opened so I had to reopen the file in order for the library to reRegister, but the next thing you know it actually worked under linux like a charm. Thank you very much. Can you tell me if HM is better, More features than libde265? It seems to me that there are more updates done so I am guessing its a more up to date version. I do not know what is going on with the licensing but HM is better yes?
Anyways I'm really happy everything compiled and ran under linux 64 bit using windows 10 bash system. Thanks again, keep up the good work.

**Comment by ChristianFeldmann** [comment]
Hi. 
Good to hear that everything works for you. So you compiled YUView on linux and only got one binary? That sounds perfectly normal. On linux, all required libraries are installed seperately and loaded when needed. 
I will try to give a summary of the differences between HM and libde265:
  - Speed: Libde265 is optimized for speed and much faster
  - Signals: Currently, only libde265 supports displaying of prediction and residual data
  - Internals: Because of their internal structure, the two libraries can display a different set of internals
The main idea behind the HM plugin is that you can experiment/change something using the reference HM software and preview your bitstreams with your modified codec directly in YUView.
Christian
